### ISSUE TITLE
Retrieve value from optional as from a dictionary

### ISSUE THREAD

**Issue by pkudrel** [nlkl/Optional#22]
What is your opinion about following extension method:
```csharp
public static bool TryGetValue<T>(this Option<T> @this, out T value)
{
    value = @this.ValueOr(default(T));
    return @this.HasValue;
}
```
I know that this is not  "functional style" but it allows to write this kind of "fail-fast" code:
```csharp
void Foo() 
{
    string res;
    if (!option.TryGetValue(out res)) return ; // fail-fast
}
```

**Comment by nlkl** [comment]
Hi,

I personally do not like the pattern (`Try(out value)`) very much, mostly due to its verbosity. However, there is nothing intrinsically wrong with it as such, and is mostly a matter of preference.

The easiest thing you can do here and now, is to simply add the extension method to your projects and use it freely.

For now, I will not include it in Optional directly, but will reconsider once C# 7 is out, allowing out variables, e.g. `.TryGetValue(out int res)`

As a side note, making an initial guard on options might be an indicator of a design problem. If a method doesn't allow a value to be missing, it should not take an option as an argument, but simply the value itself. Then it would be the responsibility of the caller to either call the method or not (or whatever handling of the None-case is suitable). In this way, the method signature is much more explicit about what it expects, and therefore models the domain more precisely.

(there are, however, other situations where such a TryGetValue could be useful, but I tend to prefer a foreach loop, `MatchSome` or `MatchNone`, depending on the specific case)

**Comment by pkudrel** [comment]
Thanks a lot for all your comments and explanations. I really appreciate it. 

I completely understand your opinion about ```Try(out value)``` pattern. For a long time I had similar judgment. However recently I have started to think that since this is the shortest way to get something safely from the dictionary so why not to use it.

I agree with your opinion about the initial guard pattern and option type. In this example I wanted to show the shortes code which  demonstratre the ```TryGetValue``` extension. 

Best regards and many thanks you for the excellent project!
