### ISSUE TITLE
Option.None should be a value

### ISSUE THREAD

**Issue by deviousasti** [nlkl/Optional#24]
The Option type is defined as `data Option = None | Some x`.
`Option.None` should be a value. 
In the library, it is implemented as a type function.
`None<int>()` isn't semantic, since absence of a value does not carry type information.

**Comment by nlkl** [comment]
Hi,

This is partially a limitation of the type system and partially a design choice.

Once a None value is created and is to be used as an option type, it will have to have a type Option<T> where T is a concrete type. Hence, the type parameter in the None<T>() function. Otherwise, None would have to be a separate type, which would introduce a lot of problems of its own.

A "workaround" for this, which is sometimes used, is to make a specific intermediate None type, that is implicitly convertible to an Option<T>. Although it allow nice syntax such as `return Option.None`, it adds a layer of confusion that I would rather be without. For example, if you try and use such a "None" value without it first being converted to an actual Option<T>, it will not work as expected - and the extra type alone will easily cause some misunderstandings.

In Optional, I have therefore decided not to provide such a value, to keep the implementation and API as simple and explicit as possible - even if it is a little more verbose than corresponding code in F# and other functional languages.

- Nils

**Comment by deviousasti** [comment]
None would be Option<Unit>.
Have an implicit case operator to convert from Option<Unit> to None.

This would have the effect of making none a value, rather than a type
function - which it is currently.

**Comment by deviousasti** [comment]
Also, I noticed that there are instance methods on the Option struct.
These would require boxing to call - you should move everything to the
extension methods.

**Comment by nlkl** [comment]
An actual `None` value will always have a type `Option<T>`. In ML like languages, type inference makes it much less clumsy to create a value, as `T` can be inferred instead of being specified explicitly, but a None value is still of type `Option<T>`.

C# does not have such sophisticated type inference, and one has to decide how to support creating None values. The most direct translation from the F# equivalent would probably be `Option<T>.None` as a static singleton value on `Option<T>`. However, as a matter of preference, I have opted for a generic create-method instead of calling a property on a generic type (`Option.None<T>()` vs `Option<T>.None`).

It is purely a matter of my own personal aesthetic preference. Both cases require the type parameter to be specified explicitly, as type inference in C# isn't powerful enough to easily circumvent this. Performance should be no problem, as creating a simple struct (such as an option) is very cheap.

The only _workaround_ for the explicit type annotation, is to create an implicit type _conversion_ from another type. This reduces some of the clumsiness, but at the cost of unnecessary complexity in my point of view. If you have a preference for this method, you are of course very welcome to implement and use your own such type in your code, but it will, for now at least, not be part of Optional.

Regarding instance methods, your assumption is wrong. Instance methods on structs do not lead to boxing (the exception being methods derived from `object`, such as ToString(), but only in case they are not overriden in the struct itself - which they are in this case). As such, I see no value in moving these to extension methods.

/Nils

**Comment by deviousasti** [comment]
Here's a basic implementation of what I was talking about:

    public struct Unit
    {
        public static readonly Unit Default = default(Unit);
    }

    public struct Option<T>
    {
        public static readonly Option<T> None;

        public bool HasValue { get; }
        public T Value { get; }        
        public Option(T value)
        {
            Value = value;
            HasValue = true;
        }

        public static implicit operator Option<T>(Option<Unit> value)
        {
            return Option<T>.None;
        }
    }

    public static class Option
    {
        public static Option<Unit> None => Option<Unit>.None;
        public static Option<T> Some<T>(T value) => new Option<T>(value);

       //simpler operator implementation
        public static Option<TResult> SelectMany<T, TResult>(this Option<T> self, Func<T, Option<TResult>> selector)
        {            
            return self.HasValue ? selector(self.Value) : None;
        }
    }

It behaves like a true value:
```

var someint = Option.Some(2);
var somefloat = Option.Some(1f);
var none = Option.None;
someint = none; //compiles
somefloat = none; //compiles
```

**Comment by nlkl** [comment]
I am not saying that it isn't possible - it definitely is. I am just saying that it isn't going to be part of Optional for now, as a conversion is a hack that saves a tiny bit of verbosity, but adds some less-than-obvious complexity underneath.

**Comment by deviousasti** [comment]
Okay, Nils. I can respect that. :)
Good luck with your future projects!
