### ISSUE TITLE
Covariance in Either

### ISSUE THREAD

**Issue by danpantry** [nlkl/Optional#38]
Is it intended that in `Option<T, E>` (aka Either), both `T` and `E` are not covariant? I.e, I cannot do this:

````csharp
interface Thinger {
  Option<T, ErrorResult> DoSomething<T>();
}

class ErrorResult {}
class DifferentErrorResult extends ErrorResult {}

class ThingerImplementation : Thinger {
  Option<T, ErrorResult> DoSomething<T>() {
    // Compiler error: Option<T, DifferentErrorResult> cannot be implicitly converted to Option<T, ErrorResult>
    return Option.None<T, DifferentErrorResult>(new DifferentErrorResult());
  }
}
````

**Comment by nlkl** [comment]
Hi @danpantry 

Yes and no.

I would very much like Option to be covariant - the lack of covariance often makes code more verbose than it would otherwise be (as a lot more manual type annotation and casting is necessary).

Unfortunately, in C# it is only possible to add variance to interfaces (and delegates), which excludes `Option<T>` and `Option<T, TException>` as these are structs. If Optional implemented these as interfaces instead (e.g. an `IOption<T>`) it would have been possible, but I consider the benefits of `Option<>` being a struct to outweigh that of covariance.

/Nils

**Comment by nlkl** [comment]
Closing this. Feel free to open another issue for further discussions on the topic.

/ Nils
