### ISSUE TITLE
Implicit conversions between T / null and Option<T>

### ISSUE THREAD

**Issue by mario-d-s** [nlkl/Optional#53]
Wouldn't it be nice if you could do the following:

```
public Option<Foo> GetFoo()
{
    if(SomeCondition) return null;
    return new Foo();
}
```

Well, by adding the following to `Option<T>`:

```
public static implicit operator Option<T>(T valueOrNull)
{
    return valueOrNull == null ? Option.None<T>() : valueOrNull.Some();
}
```

you actually can.

Granted, it's less explicit and those who use Optional to get rid of all `null`s may shudder to see `return null`...

Any objections? If not, I'd happily open a PR while adding a few tests and whatnot.

**Comment by nlkl** [comment]
Hi

First of all, sorry for the late reply - and I'm glad to see your interest in the project!

Regarding the concrete case, it is something I gave a lot of thought initially, but decided against, as I prefer the conversions to be explicit. To elaborate a bit on that, there are multiple ways to convert something into an option, each with quite different behavior:

1) Wrap directly
```csharp
default(string).Some(); // == Some(null)
"123".Some(); // == Some("123")
```

2) Wrap with null-check (e.g. nulls are converted to None)
```csharp
default(string).SomeNotNull(); // == None()
"123".SomeNotNull(); // == Some("123")
```

3) Wrap a nullable incl. null check
```csharp
default(int?).SomeNotNull(); // == None()
((int?)123).SomeNotNull(); // == Some(123) of type Option<int?>
```

4) Convert a nullable to an option
```csharp
default(int?).ToOption(); // == None()
((int?)123).ToOption(); // == Some(123) of type Option<int>
```

... and so forth.

Due to these different way to wrap a value, I don't think an implicit conversion (corresponding to 2) described above) is such a good idea to be honest.

In practice, I find that most cases are covered more or less adequately by one of the conversion extension methods. The odd man out is the "None" case, which results in slightly more verbosity, due to the need to specify the type:

```csharp
public Option<Foo> GetFoo()
{
    if(SomeCondition) return Option.None<Foo>();
    return new Foo().Some();
}
```

However, in C# 7.1 it is actually possible to use the `default` literal as an automatically inferred None:

```csharp
public Option<Foo> GetFoo()
{
    if (SomeCondition) return default;
    return new Foo().Some();
}
```

Which is relatively concise after all (even though I personally still tend to write our the full `Option.None<T>()`).

Hope it clarifies things a bit. What are your thoughts on the above?

/ Nils

**Comment by mario-d-s** [comment]
Hello Nils,

I agree with your point of view. using the `default` literal is actually what I ended up doing!

I have not used enough features of your library to realize there were so many ways for conversion. But I must congratulate you for the extensive documentation! This should certainly satisfy everyone's needs according to their preferences.
